#[cfg(not(target_arch = "wasm32"))]
pub mod apps;
pub mod builtins;
#[cfg(not(target_arch = "wasm32"))]
pub mod cli;
pub mod core;
#[cfg(not(target_arch = "wasm32"))]
pub mod crud_web_fe;
pub mod memory;
pub mod rune_ast;
pub mod rune_parser;
pub mod util;
#[cfg(not(target_arch = "wasm32"))]
pub mod lambda_main;
pub mod arithmetic;
pub mod execution;
pub mod vectrune;
pub mod wasm;
